# Generated by Django 4.2.2 on 2023-06-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medecin",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="medecin",
            name="genre",
            field=models.CharField(
                choices=[("M", "MASCULIN"), ("F", "FEMININ")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="medecin",
            name="specialite",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="adresse",
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
